sudo: required
language: bash
services:
  - docker
before_install:
  - wget -nc -P "$TRAVIS_BUILD_DIR/import" "http://download.geofabrik.de/europe/liechtenstein-160601.osm.pbf"
  - docker-compose pull import-external export import-osm postgis
  # Avoid building really expensive images
  - make fast
script:
  # Test import
  - docker-compose up -d postgis
  - sleep 10
  - docker-compose run import-external
  - docker-compose run import-osm
  - docker-compose run import-sql
  # Test local export
  - docker-compose run export
  # Test changed tiles
  - docker-compose run update-osm-diff
  - docker-compose run import-osm-diff
  - docker-compose run changed-tiles
  - docker-compose run generate-diff-jobs
  - docker-compose scale export-worker=1
  - sleep 30
  - docker-compose scale export-worker=0
  - docker-compose run merge-jobs
