sudo: required
language: bash
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - wget -nc -P "$HOME/cache" "https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf"
  - mkdir -p "$TRAVIS_BUILD_DIR/import" && cp "$HOME/cache/zurich_switzerland.osm.pbf" "$TRAVIS_BUILD_DIR/import"
  - docker-compose build
script:
  - docker-compose up -d postgis
  - sleep 10
  - docker-compose run import-water
  - docker-compose run import-sql
  - docker-compose run import
  - docker-compose run export
  - docker-compose up -d serve
  - sleep 5
  - curl "http://localhost:8080/index.json"
cache:
  directories:
    - $HOME/cache
