sudo: required
language: bash
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - docker-compose up -d postgis
script:
  - sleep 7
  - docker-compose run imposm3
