sudo: required
language: bash
services:
  - docker
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - wget -nc -P "$HOME/cache" "http://download.geofabrik.de/europe/liechtenstein-160101.osm.pbf"
  - mkdir -p "$TRAVIS_BUILD_DIR/import" && cp "$HOME/cache/liechtenstein-160101.osm.pbf" "$TRAVIS_BUILD_DIR/import"
  - docker-compose build
  - make fast
script:
  - docker-compose up -d postgis
  - sleep 5
  - docker-compose up -d pgbouncer
  - sleep 5
  - docker-compose run import-osm
  - docker-compose run import-natural-earth
  - docker-compose run import-water
  - docker-compose run import-labels
  - docker-compose run import-sql
  - docker-compose run update-scaleranks
  - docker-compose run export
  - docker-compose run update-osm-diff
  - docker-compose run import-osm-diff
  - docker-compose run changed-tiles
  - docker-compose up -d serve
  - sleep 5
cache:
  directories:
    - $HOME/cache
