name: OSM2VectorTiles
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables"]
highlighter: pygments
full_url: 'http://osm2vectortiles.org'
tweet: "Create a custom base map in minutes with free vector tiles from OpenStreetMap data."
