## Site settings
name: OSM2VectorTiles
permalink: pretty
full_url: 'http://osm2vectortiles.org'
tweet: "Create a custom base map in minutes with free vector tiles from OpenStreetMap data."

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
highlighter: rouge