pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/import
postgis:
  build: ./database/postgis
  volumes_from:
   - pgdata
  ports:
   - "5432"
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
imposm3:
  build: ./import/imposm3
  volumes:
   - ./volumes/import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
    PBF_DOWNLOAD_URL: "https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf"
water:
  build: ./import/water
  volumes:
  - ./volumes/water:/data/import
  links:
  - postgis:db
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
    # WATER_SHP_DOWNLOAD_URL: "http://data.openstreetmapdata.com/water-polygons-split-3857.zip"
jobmaker:
  build: ./export/jobmaker
  environment:
    AWS_ACCESS_KEY:
    AWS_SECRET_ACCESS_KEY:
    AWS_REGION: "eu-central-1"
    TASK_ZOOM_LEVEL: 8
    QUEUE_NAME: "osm2vectortiles_jobs"
worker:
  build: ./export/worker
  volumes:
   - ./open-streets.tm2source:/data/tm2source
   - ./volumes/export:/data/export
  links:
   - postgis:db
  environment:
    AWS_ACCESS_KEY:
    AWS_SECRET_ACCESS_KEY:
    AWS_REGION: "eu-central-1"
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
    BBOX: "8.4375 46.07323062540838 9.84375 47.040182144806664"
    SCHEME: "pyramid"
    MIN_ZOOM: "8"
    MAX_ZOOM: "14"
tileserver:
  build: ./tileserver
  volumes:
   - ./volumes/export:/data
  ports:
   - "8080:80"
