version: '2'
services:
  postgres:
    image: "osm2vectortiles/postgis"
    volumes:
     - pgdata:/var/lib/postgresql/data
    ports:
     - "5432"
    env_file: .env
  import-osm:
    image: "osm2vectortiles/import-osm"
    command: ./import-pbf.sh
    env_file: .env
    volumes:
     - ./import:/import
     - cache:/cache
    links:
    - postgres:postgres
  import-external:
    image: "osm2vectortiles/import-external"
    env_file: .env
    links:
    - postgres:postgres
  export-mbtiles:
    image: "osm2vectortiles/export"
    command: ./export-local.sh
    volumes:
    - ./export:/export
    - ./osm2vectortiles.tm2source:/tm2source
    links:
    - postgres:postgres
    env_file: .env
    environment:
      BBOX: "-22.5,79.6871841545,-21.09375,79.9359182463"
      MIN_ZOOM: "0"
      MAX_ZOOM: "14"
  import-sql:
    image: "osm2vectortiles/import-sql"
    env_file: .env
    links:
    - postgres:postgres
    environment:
      SQL_CREATE_INDIZES: 'false'
volumes:
  pgdata:
  cache:
