pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/import
postgis:
  build: ./database/postgis
  volumes_from:
   - pgdata
  ports:
   - "5432:5432"
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
imposm3:
  build: ./database/imposm3
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
    PBF_DOWNLOAD_URL: "https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf"
importwater:
  build: ./database/importwater
  volumes:
  - ./import:/data/import
  links:
  - postgis:db
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
    # WATER_SHP_DOWNLOAD_URL: "http://data.openstreetmapdata.com/water-polygons-split-3857.zip"
tilelive:
  build: ./database/tilelive
  volumes:
   - ./osm-bright-2.tm2source:/data/tm2source
   - ./export:/data/export
  links:
   - postgis:db
  environment:
    OSM_DB: "osm_zurich"
    OSM_USER: "osm"
    OSM_PASSWORD: "suisse"
    BBOX: "8.4039 47.3137 8.6531 47.4578"
    MIN_ZOOM: "0"
    MAX_ZOOM: "14"
tileserver:
  build: ./tileserver
  volumes:
   - ./export:/data
  ports:
   - "8080:80"
