pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/cache
postgis:
  build: ./src/postgis
  volumes_from:
   - pgdata
  ports:
   - "5432"
import:
  build: ./src/import
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
import-water:
  build: ./src/import-water
  links:
  - postgis:db
enqueue-jobs:
  build: ./src/enqueue-jobs
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_REGION: "eu-central-1"
    TASK_ZOOM_LEVEL: 8
    QUEUE_NAME: "osm2vectortiles_jobs"
export:
  build: ./src/export
  volumes:
   - ./export:/data/export
  links:
   - postgis:db
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_REGION: "eu-central-1"
    BBOX: "8.4375 46.07323062540838 9.84375 47.040182144806664"
    MIN_ZOOM: "8"
    MAX_ZOOM: "14"
serve:
  build: ./src/serve
  volumes:
   - ./export:/data
  ports:
   - "8080:80"
