pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/cache
postgis:
  build: ./src/postgis
  volumes_from:
   - pgdata
  ports:
   - "5432"
import:
  build: ./src/import
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
import-water:
  build: ./src/import-water
  links:
  - postgis:db
export:
  build: ./src/export
  volumes:
   - ./export:/data/export
  links:
   - postgis:db
  environment:
    BBOX: "8.4039 47.3137 8.6531 47.4578"
    MIN_ZOOM: "0"
    MAX_ZOOM: "14"
serve:
  build: ./src/serve
  volumes:
   - ./export:/data
  ports:
   - "8080:80"
