pgdata:
  image: "tianon/true"
  volumes:
  - /var/lib/postgresql/data
cache:
  image: "tianon/true"
  volumes:
  - /data/cache
postgis:
  build: ./src/postgis
  volumes_from:
   - pgdata
  ports:
   - "5432"
pgbouncer:
  build: ./src/pgbouncer
  links:
   - postgis:pg
  ports:
   - "6432"
import-osm:
  build: ./src/import-osm
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
import-labels:
  build: ./src/import-external
  command: ./import-labels.sh
  links:
  - postgis:db
import-natural-earth:
  build: ./src/import-external
  command: ./import-natural-earth.sh
  links:
  - postgis:db
import-water:
  build: ./src/import-external
  command: ./import-water.sh
  links:
  - postgis:db
import-external:
  build: ./src/import-external
  links:
  - postgis:db
update-scaleranks:
  build: ./src/update-scaleranks
  links:
  - postgis:db
enqueue-jobs:
  build: ./src/enqueue-jobs
  environment:
    AWS_REGION: "eu-central-1"
    TASK_ZOOM_LEVEL: 8
    QUEUE_NAME: "osm2vectortiles_jobs"
export-remote:
  build: ./src/export
  command: ./export-remote.sh
  volumes:
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
  environment:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    AWS_REGION: "eu-central-1"
export-local:
  build: ./src/export
  command: ./export-local.sh
  volumes:
   - ./export:/data/export
   - ./open-streets.tm2source:/data/tm2source
  links:
   - pgbouncer:db
  environment:
    BBOX: "8.4375 46.07323062540838 9.84375 47.040182144806664"
    MIN_ZOOM: "8"
    MAX_ZOOM: "14"
serve:
  build: ./src/serve
  volumes:
   - ./export:/data
  ports:
   - "8080:80"
import-sql:
  build: ./src/import-sql
  links:
   - postgis:db
mapbox-studio:
  build: ./tools/mapbox-studio
  volumes:
   - ./open-streets.tm2source:/projects/open-streets.tm2source
  links:
   - postgis:db
  ports:
   - "3000:3000"
compare-visual:
  build: ./tools/compare-visual
  ports:
   - "4000:3000"
   - "4001:3001"
  links:
   - serve:tileserver
